-
  name: Deploy a web application
  hosts: db_and_web_server
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install dependencies
      apt: name={{ item }} state=latest 
      with_items:
       - python3
       - python3-setuptools
       - python3-dev
       - build-essential
       - python3-pip
       - python3-mysqldb

    - include: tasks/deploy_apache.yml
  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted
